from abc import ABC, abstractmethod
from typing import Optional
from backend.models.knowledge_object import KnowledgeObject


class BaseDocumentStore(ABC):
    @abstractmethod
    def put(self, obj: KnowledgeObject) -> None: ...
    @abstractmethod
    def get(self, id: str) -> Optional[KnowledgeObject]: ...
    @abstractmethod
    def list_all(self) -> list[KnowledgeObject]: ...
    @abstractmethod
    def query(self, **filters) -> list[KnowledgeObject]: ...
    @abstractmethod
    def clear(self) -> None: ...


class BaseVectorStore(ABC):
    @abstractmethod
    def upsert(self, id: str, embedding: list[float], text: str, metadata: dict) -> None: ...
    @abstractmethod
    def search(self, query_embedding: list[float], top_k: int, filters: Optional[dict]) -> list[dict]: ...
    @abstractmethod
    def count(self) -> int: ...
    @abstractmethod
    def clear(self) -> None: ...


class BasePipelineStore(ABC):
    @abstractmethod
    def save_run(self, run: dict) -> None: ...
    @abstractmethod
    def get_runs(self, limit: int) -> list[dict]: ...
