services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./Sample_Data:/app/Sample_Data
      - ./backend/app/config:/app/backend/app/config

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE=http://localhost:8000/api
    depends_on:
      - backend
