"""Report generator: compiles deployment and test results into a markdown report."""

import os
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from .utils import logger, print_phase


@dataclass
class ReportData:
    branch_name: str = ""
    merge_conflicts: list[str] = field(default_factory=list)
    built_images: list[str] = field(default_factory=list)
    fixed_packages: list[str] = field(default_factory=list)
    env_name: str = ""
    rg_name: str = ""
    location: str = ""
    image_tag: str = ""
    use_case: str = ""
    web_app_url: str = ""
    api_app_url: str = ""
    deploy_success: bool = False
    test_summary: str = ""
    test_success: bool = False
    cleanup_message: str = ""
    cleanup_success: bool = False
    errors: list[str] = field(default_factory=list)


def generate(data: ReportData, output_path: Optional[str] = None) -> str:
    """Generate a comprehensive deployment validation report."""
    print_phase("Report Generation")

    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    overall = "✅ PASS" if (data.deploy_success and data.test_success) else "❌ FAIL"

    lines = [
        f"# Deployment Validation Report",
        f"",
        f"**Date:** {now}  ",
        f"**Overall Result:** {overall}  ",
        f"**Branch:** `{data.branch_name}`  ",
        f"",
        f"---",
        f"",
        f"## 1. Deployment Details",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Environment Name | `{data.env_name}` |",
        f"| Resource Group | `{data.rg_name}` |",
        f"| Azure Region | `{data.location}` |",
        f"| Docker Image Tag | `{data.image_tag}` |",
    ]
    if data.use_case:
        lines.append(f"| Use Case | `{data.use_case}` |")
    lines.extend([
        f"| Web App URL | {data.web_app_url} |",
        f"| API App URL | {data.api_app_url} |",
        f"| Deploy Status | {'✅ Success' if data.deploy_success else '❌ Failed'} |",
        f"",
        f"## 2. Docker Images",
        f"",
    ])

    if data.built_images:
        lines.append("| Image |")
        lines.append("|-------|")
        for img in data.built_images:
            lines.append(f"| `{img}` |")
    else:
        lines.append("_No images built (skipped or pre-existing)._")
    lines.append("")

    if data.fixed_packages:
        lines.extend([
            f"### Auto-Fixed Packages",
            f"",
            f"The following packages had version issues that were automatically fixed:",
            f"",
        ])
        for pkg in data.fixed_packages:
            lines.append(f"- {pkg}")
        lines.append("")

    lines.extend([f"## 3. E2E Test Results", f""])
    lines.append(data.test_summary if data.test_summary else "_No test results available._")

    lines.extend([
        f"", f"## 4. Cleanup", f"",
        f"| Action | Status |",
        f"|--------|--------|",
        f"| Resource Group Deletion | {'✅' if data.cleanup_success else '⏳'} {data.cleanup_message} |",
        f"",
    ])

    if data.merge_conflicts:
        lines.extend([f"## 5. Merge Conflicts (Auto-Resolved)", f""])
        for c in data.merge_conflicts:
            lines.append(f"- `{c}`")
        lines.append("")

    if data.errors:
        lines.extend([f"## Errors Encountered", f""])
        for e in data.errors:
            lines.append(f"- {e}")
        lines.append("")

    lines.extend([f"## Recommendation", f""])
    if data.deploy_success and data.test_success:
        lines.append("✅ **Safe to merge** — All dependency changes are compatible and tests pass.")
    elif data.deploy_success and not data.test_success:
        lines.append("⚠️ **Needs investigation** — Deployment succeeded but some tests failed.")
    else:
        lines.append("❌ **Do not merge** — Deployment failed. Review errors above.")

    lines.extend(["", "---", f"_Report generated by deploy-test skill at {now}_"])

    report = "\n".join(lines)

    if output_path:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(report)
        logger.info("✔ Report saved to: %s", output_path)

    return report
